services:
  - type: web
    name: whiteout-survival-signup
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: HOST_PIN
        sync: false
